defaults:
  - model_summary
  - rich_progress_bar
  - lr_monitor
  - _self_

model_summary:
  max_depth: -1

val_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: ???
  monitor: ???
  mode: ???
  save_last: True
  auto_insert_metric_name: False
  save_top_k: 3
  every_n_train_steps: 5000

step_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "step_{step:06d}"
  monitor: "step"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False
  save_top_k: 1
  every_n_train_steps: 5000
